### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by bill-e-ghote** [TrimarcJake/cheese-swiss-snippets#1]
The README mentions two subdirectories and files that are not included in this repo. Is that by design or mistake?
•	CA\AuditFilter
•	policy\EditFlags

**Comment by jakehildreth** [comment]
Heya! “CA\AuditFilter” and “policy\EditFlags” are configuration options for the certutil commands and not subdirectories/files.

**Comment by bill-e-ghote** [comment]
Thank you for expanding my knowledge and understanding. Apologies for the noise!
